#!/usr/bin/env python3

import os
import shutil
import sys
from typing import NoReturn
from urllib.parse import urlparse

# These should stay in sync with ruyi_backend/config/env.py
ENV_DB_MAIN_DSN = "RUYI_BACKEND_DB_MAIN__DSN"
ENV_DB_MAIN_NAME = "RUYI_BACKEND_DB_MAIN__NAME"


def probe_mysql_binary() -> str | None:
    path = os.environ.get("PATH", "")
    if x := shutil.which("mariadb", path=path):
        return x
    elif x := shutil.which("mysql", path=path):
        return x
    return None

def main() -> NoReturn:
    # These should stay in sync with ruyi_backend/config/env.py
    db_dsn = os.environ.get(ENV_DB_MAIN_DSN, "")
    db_name = os.environ.get(ENV_DB_MAIN_NAME, "ruyisdk")
    if not db_dsn or not db_name:
        sys.exit(1)

    u = urlparse(db_dsn)
    if not u.scheme.startswith("mysql"):
        sys.exit(2)

    hostname = u.hostname
    if not hostname:
        sys.exit(3)

    port = u.port or 3306

    mysql_binary = probe_mysql_binary()
    if mysql_binary is None:
        sys.exit(4)

    argv: list[str] = [
        mysql_binary,
        "-h", hostname,
        "-P", str(port),
    ]

    if u.username:
        argv.extend(["-u", u.username])

    if u.password:
        argv.extend(["-p" + u.password])

    argv.extend(["-D", db_name])
    argv.extend(sys.argv[1:])

    os.execv(mysql_binary, argv)


if __name__ == "__main__":
    main()
