name: CI

on:
  push:
    paths:
      - pyproject.toml
      - poetry.lock
      - '**.py'
    tags:
      - '*'
  pull_request:
    paths:
      - pyproject.toml
      - poetry.lock
      - '**.py'
  merge_group:
    types: [checks_requested]

jobs:
  lint:
    name: 'ruff & mypy & pytest'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Poetry
        run: pipx install poetry
      - uses: actions/setup-python@v5
        with:
          python-version-file: 'pyproject.toml'
          cache: poetry
      - name: Install deps
        run: poetry install --with=dev
      - name: Lint with ruff
        run: poetry run ruff check
      - name: Type-check with mypy
        run: poetry run mypy
      - name: Test with pytest
        run: poetry run pytest

  pylic:
    name: license compatibility
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Poetry
        run: pipx install poetry
      - uses: actions/setup-python@v5
        with:
          python-version-file: 'pyproject.toml'
          cache: poetry
      - name: Install runtime deps
        run: poetry install --only=main
      - name: Install pylic
        run: poetry run pip install pylic
      - name: List all licenses involved
        run: poetry run pylic list
      - name: Check license compatibility with pylic
        run: poetry run pylic check
